### ISSUE TITLE
If a given anime has been already added to the user's list, the "Add Anime" button should be changed to say "Added."

### ISSUE THREAD

**Issue by christopherbarnett** [ucsb-cs148-f21/project-t10-animelist#58]
Acceptance Criteria:
- [ ]  Previously added anime should not display an "add" button after a search.
- [ ] Once an anime is added, the add button should automatically be updated to say "added"
- [ ] Given an anime that is already added, the user should NOT be able to add it twice to their list.

**Comment by jvoucsb** [comment]
Closed by #133
