### ISSUE TITLE
Display feedback after saving an edited user list entry

### ISSUE THREAD

**Issue by rowantran** [ucsb-cs148-f21/project-t10-animelist#71]
There is currently no feedback displayed after saving an entry in the user's list.

Acceptance criteria:
- [ ] After clicking "Save" on an edited list entry, a dialog should pop up informing the user of the operation's outcome.
- [ ] A successful save should show a success message.
- [ ] An unsuccessful save should show a failure message.
- [ ] Both the success and failure dialogs use icons and color appropriately to immediately convey the appropriate message.

**Comment by jvoucsb** [comment]
Closed #133 

Displays a toast as feedback if the user edited an item
